# -*- coding: utf-8 -*-
"""DDL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vMK1O-2_zXCil5ZRXu-6l4s4kgKpNwg

CRUD - CREATE, READ, UPDATE DELETE
"""

!pip install mysql-connector-python

import mysql.connector
import pandas as pd

host = '34.70.26.188' # endereço do banco externo que eu quero acessar
user = 'root'
password = ''
database = 'locadora'

!curl ipecho.net/plain

def consulta(query, tabela):
  connection = mysql.connector.connect(
      host = host,
      user = user,
      password = password,
      database = database
  )
  cursor = connection.cursor()

  try:
    cursor.execute(query)
    result = cursor.fetchall()
    globals()[tabela] = pd.DataFrame(result, columns=cursor.column_names)
    display(globals()[tabela])
  finally:
    cursor.close()
    connection.close()

def ddl(comando):
    connection = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    cursor = connection.cursor()

    try:
        cursor.execute(comando)
        connection.commit()  # Confirma as mudanças no banco
        print(f"Comando DDL executado com sucesso:\n{comando}")
    except mysql.connector.Error as err:
        print(f"Erro ao executar o comando DDL: {err}")
    finally:
        cursor.close()
        connection.close()

consulta('''
SHOW TABLES;
''',''' ''')

"""# C do CRUD

## Criação e Modificação de Tabelas
"""

# Criar tabela pagamentos
ddl('''
CREATE TABLE pagamentos (
    codpagamento INT PRIMARY KEY,
    codaluguel INT,
    valor FLOAT,
    data_pagamento DATE,
    FOREIGN KEY (codaluguel) REFERENCES aluguel (codaluguel)
);
''')

consulta('''
SHOW TABLES;
''',''' ''')

# Adicionar coluna email em cliente
ddl('''
ALTER TABLE cliente ADD COLUMN email VARCHAR(255);
''')

consulta('''
DESC cliente;
''','''''')

# Alterar tipo da coluna valor em carro
ddl('''
ALTER TABLE carro MODIFY COLUMN valor DECIMAL(10,2);
''')

consulta('''
DESC carro;
''','''''')

# Renomear coluna estado para uf em cliente
ddl('''
ALTER TABLE cliente CHANGE COLUMN estado uf CHAR(2);
''')

consulta('''
DESC cliente;
''','''''')

# Adicionar NOT NULL na coluna marca em marca
ddl('''
ALTER TABLE marca MODIFY COLUMN marca VARCHAR(255) NOT NULL;
''')

consulta('''
DESCRIBE marca;
''',''' ''')

# Remover coluna estadocivil em cliente
ddl('''
ALTER TABLE cliente DROP COLUMN estadocivil;
''')

consulta('''
DESCRIBE cliente;
''',''' ''')

# Excluir tabela pagamentos
ddl('''
DROP TABLE pagamentos;
''')

# Remover coluna data_aluguel em aluguel
ddl('''
ALTER TABLE aluguel DROP COLUMN data_aluguel;
''')

# DELETAR Banco locadora
ddl('''
DROP DATABASE locadora;
''')

"""# Reconstruíndo o banco locadora"""

ddl('''
CREATE TABLE cliente(
codcliente INT PRIMARY KEY,
nome VARCHAR(50),
cidade VARCHAR(50),
sexo CHAR(1),
estado CHAR(2),
estadocivil CHAR(1)
);
''')

ddl('''
CREATE TABLE marca(
codmarca INT PRIMARY KEY,
marca VARCHAR(30)
);
''')

ddl('''
CREATE TABLE carro(
codcarro INT PRIMARY KEY,
codmarca INT,
modelo VARCHAR(30) NOT NULL,
valor FLOAT,
FOREIGN KEY (codmarca) REFERENCES marca (codmarca)
);
''')

ddl('''
CREATE TABLE aluguel(
codaluguel INT PRIMARY KEY,
codcliente INT,
codcarro INT,
data_aluguel DATE,
FOREIGN KEY (codcliente) REFERENCES cliente (codcliente),
FOREIGN KEY (codcarro) REFERENCES carro (codcarro)
);
''')

ddl('''
INSERT INTO cliente (codcliente, nome, cidade, sexo, estado, estadocivil)
VALUES
(1, 'Ana Silva', 'Duque de Caxias', 'F', 'RJ', 'C'),
(2, 'Bruna Pereira', 'Niterói', 'F', 'RJ', 'C'),
(3, 'Túlio Nascimento', 'Duque de Caxias', 'M', 'RJ', 'S'),
(4, 'Fernando Souza', 'Campinas', 'M', 'SP', 'S'),
(5, 'Lúcia Andrade', 'São Paulo', 'F', 'SP', 'C');
''')

ddl('''
INSERT INTO marca (codmarca, marca) VALUES
(1, 'Ford'),
(2, 'Fiat'),
(3, 'Chevrolet'),
(4, 'Volkswagen'),
(5, 'Renault');
''')

ddl('''
INSERT INTO carro (codcarro, modelo, codmarca, valor) VALUES
(1, 'Ka', 1, 100.00),
(2, 'Argo', 2, 150.00),
(3, 'Onix', 3, 170.00),
(4, 'Polo', 4, 150.00),
(5, 'Kwid', 5, 120.00);
''')

ddl('''
INSERT INTO aluguel (codaluguel, codcliente, codcarro, data_aluguel)VALUES
(1, 3, 2, '2023-04-01'),
(2, 2, 1, '2023-04-02'),
(3, 2, 1, '2023-04-03'),
(4, 2, 3, '2023-04-04'),
(5, 1, 4, '2023-04-05'),
(6, 1, 4, '2023-04-13'),
(7, 1, 1, '2023-04-15'),
(8, 5, 2, '2023-04-19'),
(9, 5, 2, '2023-04-21'),
(10,3, 1, '2023-04-25');
''')

# Inserir cliente "João Silva"
ddl('''
INSERT INTO cliente (codcliente, nome, cidade, estado, estadocivil)
VALUES (6, 'João Silva', 'São Paulo', 'SP', 'S');
''')

# Inserir marca "Toyota"
ddl('''
INSERT INTO marca (codmarca, marca)
VALUES (6, 'Toyota');
''')

# Inserir carro "Corolla"
ddl('''
INSERT INTO carro (codcarro, codmarca, modelo, valor)
VALUES (6, 6, 'Corolla', 900);
''')

#  Inserir aluguel para cliente 1 e carro 2 na data atual
ddl('''
INSERT INTO aluguel (codaluguel, codcliente, codcarro, data_aluguel)
VALUES (11, 1, 2, CURDATE());
''')

# Inserir marca "Mercedes"
ddl('''
INSERT INTO marca (codmarca, marca)
VALUES (7, 'Mercedes');
''')

ddl('''
INSERT INTO carro (codcarro, codmarca, modelo, valor)
VALUES
(7, 7, 'C-280', 60000),
(8, 7, 'E-320', 90000),
(9, 7, 'SLK-320', 70000);
''')

consulta('''
select * from carro;
''','''''')

# Inserir aluguel para cliente 2 e carro 3 na data de ontem
ddl('''
INSERT INTO aluguel (codaluguel, codcliente, codcarro, data_aluguel)
VALUES (12, 2, 3, DATE_SUB(CURDATE(), INTERVAL 1 DAY));
''')

consulta('''
select * from aluguel;
''','''''')

"""# UPDATE"""

# Atualizar nome do cliente 1
ddl('''
UPDATE cliente
SET nome = 'Ana Silva Ribeiro'
WHERE codcliente = 1;
''')

consulta('''
select * from cliente;
''','''''')

consulta('''
select * from carro;
''','''''')

# Modificar valor do carro 3
ddl('''
UPDATE carro
SET valor = 200
WHERE codcarro = 3;
''')

consulta('''
select * from carro;
''','''''')

# Deletar Kwid da base srsrsrsrs
ddl('''
DELETE FROM carro
WHERE modelo = 'Kwid';
''')

consulta('''
select * from carro;
''','''''')

consulta('''
select * from cliente;
''','''''')

# Deletar o cliente 5 da base aluguel
ddl('''
DELETE FROM aluguel
WHERE codcliente = '5';
''')

# Deletar o cliente 5 da base cliente
ddl('''
DELETE FROM cliente
WHERE codcliente = '5';
''')

consulta('''
select * from aluguel;
''','''''')

# Remover cliente 4
ddl('''
DELETE FROM cliente
WHERE codcliente = 4;
''')