# -*- coding: utf-8 -*-
"""frota

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqvBH1VYPTimPk30Cevu6DzIVLi7gDeL
"""

import pandas as pd

cliente = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRizO37GDBc5KOKED10_N0ndnAX3jQE4qi_VeL6v9BBSgX3uePV-HFcN56gDF-61QPBOV83zuvi4tkZ/pub?gid=1986097323&single=true&output=csv')
cliente

veiculo = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRizO37GDBc5KOKED10_N0ndnAX3jQE4qi_VeL6v9BBSgX3uePV-HFcN56gDF-61QPBOV83zuvi4tkZ/pub?gid=2061311847&single=true&output=csv')
veiculo

frete = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRizO37GDBc5KOKED10_N0ndnAX3jQE4qi_VeL6v9BBSgX3uePV-HFcN56gDF-61QPBOV83zuvi4tkZ/pub?gid=124219553&single=true&output=csv')
frete.rename(columns={'Peso (KG)':'Peso'},inplace=True)
frete

km = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRizO37GDBc5KOKED10_N0ndnAX3jQE4qi_VeL6v9BBSgX3uePV-HFcN56gDF-61QPBOV83zuvi4tkZ/pub?gid=1353331406&single=true&output=csv')
km.rename(columns={'Manut.':'Manutencao'},inplace=True)
km

from google.colab import files
from google.cloud import bigquery
from google.colab import auth


# Autenticar no Google Cloud
auth.authenticate_user()

# Criar o cliente do BigQuery
client = bigquery.Client()

# Definir o ID do projeto e o ID da tabela
project_id = 'turmas-dados'
table_id = 'turmas-dados.logistica2.cliente'

# Enviar o DataFrame para o BigQuery
cliente.to_gbq(table_id, project_id=project_id, if_exists='replace')

from google.colab import files
from google.cloud import bigquery
from google.colab import auth


# Autenticar no Google Cloud
auth.authenticate_user()

# Criar o cliente do BigQuery
client = bigquery.Client()

# Definir o ID do projeto e o ID da tabela
project_id = 'turmas-dados'
table_id = 'turmas-dados.logistica2.veiculo'

# Enviar o DataFrame para o BigQuery
veiculo.to_gbq(table_id, project_id=project_id, if_exists='replace')

from google.colab import files
from google.cloud import bigquery
from google.colab import auth


# Autenticar no Google Cloud
auth.authenticate_user()

# Criar o cliente do BigQuery
client = bigquery.Client()

# Definir o ID do projeto e o ID da tabela
project_id = 'turmas-dados'
table_id = 'turmas-dados.logistica2.frete'

# Enviar o DataFrame para o BigQuery
frete.to_gbq(table_id, project_id=project_id, if_exists='replace')

from google.colab import files
from google.cloud import bigquery
from google.colab import auth


# Autenticar no Google Cloud
auth.authenticate_user()

# Criar o cliente do BigQuery
client = bigquery.Client()

# Definir o ID do projeto e o ID da tabela
project_id = 'turmas-dados'
table_id = 'turmas-dados.logistica2.km'

# Enviar o DataFrame para o BigQuery
km.to_gbq(table_id, project_id=project_id, if_exists='replace')