# -*- coding: utf-8 -*-
"""Projeto ETL SQL to Cloud Storage - Aline Melo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6Aiq7gdTLaFBGuL5HWiCuYNJX3EgjRB
"""

!pip install mysql-connector-python

import mysql.connector
import pandas as pd

host = '34.69.233.123'
user = 'root'
password = ''
database = 'loja'

!curl ipecho.net/plain

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = 'show tables;'
cursor.execute(query)
result = cursor.fetchall()
tabelas = pd.DataFrame(result,columns=cursor.column_names)
display(tabelas)
cursor.close()
connection.close()

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM Cliente;
'''
cursor.execute(query)
result = cursor.fetchall()
cliente = pd.DataFrame(result, columns=cursor.column_names)
display(cliente)
cursor.close()
connection.close()

from google.colab import auth
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
from google.cloud import storage
client = storage.Client()
bucket_name = 'desafio-3-loja'
bucket = client.bucket(bucket_name)
cliente.to_csv('cliente.csv', index=False)
destination_blob_name = 'tabela/cliente.csv'
source_file_name = 'cliente.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM Pedido;
'''
cursor.execute(query)
result = cursor.fetchall()
pedido = pd.DataFrame(result, columns=cursor.column_names)
display(pedido)
cursor.close()
connection.close()

from google.colab import auth
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
from google.cloud import storage
client = storage.Client()
bucket_name = 'desafio-3-loja'
bucket = client.bucket(bucket_name)
cliente.to_csv('pedido.csv', index=False)
destination_blob_name = 'tabela/pedido.csv'
source_file_name = 'pedido.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM Produto;
'''
cursor.execute(query)
result = cursor.fetchall()
produto = pd.DataFrame(result, columns=cursor.column_names)
display(produto)
cursor.close()
connection.close()

from google.colab import auth
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
from google.cloud import storage
client = storage.Client()
bucket_name = 'desafio-3-loja'
bucket = client.bucket(bucket_name)
cliente.to_csv('produto.csv', index=False)
destination_blob_name = 'tabela/produto.csv'
source_file_name = 'produto.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM ItemPedido;
'''
cursor.execute(query)
result = cursor.fetchall()
itemproduto = pd.DataFrame(result, columns=cursor.column_names)
display(itemproduto)
cursor.close()
connection.close()

from google.colab import auth
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
from google.cloud import storage
client = storage.Client()
bucket_name = 'desafio-3-loja'
bucket = client.bucket(bucket_name)
cliente.to_csv('itemproduto.csv', index=False)
destination_blob_name = 'tabela/itemproduto.csv'
source_file_name = 'itemproduto.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM Categoria;
'''
cursor.execute(query)
result = cursor.fetchall()
categoria = pd.DataFrame(result, columns=cursor.column_names)
display(categoria)
cursor.close()
connection.close()

from google.colab import auth
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
from google.cloud import storage
client = storage.Client()
bucket_name = 'desafio-3-loja'
bucket = client.bucket(bucket_name)
cliente.to_csv('categoria.csv', index=False)
destination_blob_name = 'tabela/categoria.csv'
source_file_name = 'categoria.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
    database=database,
)
cursor = connection.cursor()
query = '''
SELECT * FROM ProdutoCategoria;
'''
cursor.execute(query)
result = cursor.fetchall()
produtocategoria = pd.DataFrame(result, columns=cursor.column_names)
display(produtocategoria)
cursor.close()
connection.close()

from google.colab import auth
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
from google.cloud import storage
client = storage.Client()
bucket_name = 'desafio-3-loja'
bucket = client.bucket(bucket_name)
cliente.to_csv('produtocategoria.csv', index=False)
destination_blob_name = 'tabela/produtocategoria.csv'
source_file_name = 'produtocategoria.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)