# -*- coding: utf-8 -*-
"""Consulta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpF3MBNhfYmc2-TMyLOmou6HoXWmSYEp
"""

!pip install mysql-connector-python

import mysql.connector
import pandas as pd

host = '34.69.233.123'
user =''
password = ''
database = 'loja'

!curl ipecho.net/plain

def consulta(query, tabela):
  connection = mysql.connector.connect(
      host = host,
      user = user,
      password = password,
      database = database
  )
  cursor = connection.cursor()

  try:
    cursor.execute(query)
    result = cursor.fetchall()
    columns = [desc[0] for desc in cursor.description]
    globals()[tabela] = pd.DataFrame(result, columns=columns)
    display(globals()[tabela])
  finally:
    cursor.close()
    connection.close()

consulta('''
SHOW TABLES;
''', 'tabelas')

"""SELECT"""

'''
Está clásula serve paar selecionar um ou mais  atributos (colunas)
de uma ou mais tabelas

Exemple: selecionar os registros para os atributos nome da Cliente

'''

consulta('''
Select nome
From Cliente
''', 'nomes_Clientes')

'''
Exemple: selecionar os registros para os atributos id e o
atributos nome da tabela Cliente

'''

consulta('''
Select id_Cliente, nome
From Cliente
''', 'id_nomes_Clientes')

'''
Exemple: selecionar os registros para todos atributos da tabela Cliente

'''

consulta('''
Select *
From Cliente
''', 'clientes')

'''
Consulta para tarzer todos os registros de todas as colunas da tabela categoria
'''

consulta('''
SELECT *
FROM Categoria;
''','categoria')

consulta('SELECT * FROM ItemPedido;', 'itens_pedido')

consulta('SELECT * FROM Pedido;', 'pedidos')

consulta('SELECT * FROM Produto;', 'produtos')

consulta('SELECT * FROM ProdutoCategoria;', 'produtos_categoria')

"""#WHERE"""

'''
Faça uma consulta que retorne todos os nomes e endereços de cliente
que moram no ceara
'''

consulta('''
SELECT nome, endereco
FROM Cliente
WHERE endereco = 'CE'
''','cliente_CE')

'''
Faça uma consulta que retorne todos os ids de pedidos cuja quantidade seja
maior que 30 na tebala itemPedido
'''

consulta('''
SELECT id_pedido
FROM ItemPedido
WHERE quantidade > 30;
''','grandes_pedidos')

'''
Quais são os  estdos (UFs) diferentes estão representados em nossa
tabela Clinetes
'''

consulta('''
SELECT DISTINCT endereco
FROM Cliente
''', 'UFs')

"""#LIMIT"""

'''
Imagine você deseja fazer uma consulta que retorne apenas
os cincos primeiros nomes de clientes
'''

consulta('''
SELECT nome
FROM Cliente
LIMIT 5;
''', 'primieros_clientes')

"""# Consultas com BOOLEANOS (E | U | NÃO)"""

'''
Faça uma consulta que retorne todos os douglas e que moram em SP'''

consulta('''
SELECT nome, endereco
FROM Cliente
WHERE nome = 'Douglas'
AND endereco = 'SP';
''', 'tio_douglas')

'''
faça uma consulta que retorna  todos os nomes e endereços de Douglas
que moram em SP ou MA
'''
consulta('''
SELECT nome, endereco
FROM Cliente
WHERE nome = 'Douglas' AND (endereco = 'MA' OR endereco = 'SP');
''', 'tio_douglas')

'''
Faça uma consulta que retorne todos os nomes e endereços de Clientes
que moram em SP ou MA
'''
consulta('''
SELECT nome endereco
FROM Cliente
WHERE endereco = 'MA'
OR
endereco = 'SP'
''','cleinte_2')

'''
Faça uma ocnsulta que reotrne todos os clientes que não sejam de SP
'''

consulta('''
SELECT nome, endereco
FROM Cliente
WHERE NOT endereco = 'SP';
''', 'no_sp')

"""#Funções de agregação"""

'''
Faça um aocnsulta que retorne a contagem de cliente da tabela Cliente
'''
consulta('''
SELECT count(id_cliente)
FROM Cliente;
''','contagem')

'''
faça consulta que retorne a media do atributo
quantidade da tabela ItemPedidos'''
consulta('''
SELECT AVG(quantidade) Quantidade_Media
From ItemPedido;
''','quantidade_media')

'''
faça uam consulta que retorne a quantidade do
ItemPedidos com maior quantidade '''

consulta('''
SELECT MAX(quantidade) qauntidade_maxima
FROM ItemPedido;
''','maior_pedido')

'''
faça uam consulta que retorne a quantidade do
ItemPedidos com menor quantidade '''

consulta('''
SELECT MIN(quantidade) qauntidade_minima
FROM ItemPedido;
''','maior_pedido')

'''
faça uam consulta que retorne a média do atributo quantidade
da tabela ItemPedido arredendoda com duas casas decimais '''

consulta('''
SELECT ROUND(AVG(quantidade), 2) AS quantidade_media2
FROM ItemPedido;
''', 'quantidade_media2')

'''
faça uma ocnsulta que retorne a soma de todos as quantidades
a tabela ItemPedido'''

consulta('''
SELECT SUM(quantidade) as quantidades_total
FROM ItemPedido
''', 'quantidade_total')

"""#Criar outra tabela ja esta no google cloud que RH e fazer a aula da parte da tarde."""