# -*- coding: utf-8 -*-
"""Gabarito_Projeto_AD11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKeT1x8MrZ1VoZnsLGrSPl64u1X4RkDs
"""

# Imprime o texto para indicar as opções disponíveis para o usuário.
print('Escolha o número da opção que deseja')

# Imprime as opções disponíveis para o usuário.
print('Digite 1 para cadastrar um funcionário')
print('Digite 2 para consultar um funcionário')
print('Digite 3 para atualizar um funcionário')
print('Digite 4 para remover um funcionário')

# Solicita ao usuário que informe a opção desejada.
menu = input('Informe o número da opção desejada: ')

# Verifica se a lista 'funcionarios' já foi inicializada.
if 'funcionarios' in locals():
    # Se já foi inicializada, não faz nada.
    pass
else:
    # Se não foi inicializada, cria a lista 'funcionarios' com sub-listas vazias para cada atributo do funcionário.
    funcionarios = [[],[],[],[],[],[],[],[],[]]

# Se a opção do menu escolhida for '1' (cadastrar um funcionário):
if menu == '1':
    # Entra em um loop infinito até que um ID único seja fornecido.
    while True:
        id = input('Informe o Id do funcionário: ')
        # Verifica se o ID já está cadastrado.
        if id in funcionarios[0]:
            print('Esse Id já está cadastrado!')
        else:
            # Se o ID não estiver cadastrado, adiciona-o à lista de IDs e sai do loop.
            funcionarios[0].append(id)
            break
    # Solicita ao usuário que insira os detalhes do funcionário e os adiciona às listas correspondentes.
    funcionarios[1].append(input('Informe o nome do funcionário: '))
    funcionarios[2].append(input('Informe a cidade do funcionário: '))
    funcionarios[3].append(input('Informe o estado do funcionário: '))
    funcionarios[4].append(input('Informe o email do funcionário: '))
    funcionarios[5].append(input('Informe a idade do funcionário: '))
    funcionarios[6].append(input('Informe a escolaridade do funcionário: '))
    funcionarios[7].append(input('Informe o cargo do funcionário: '))
    funcionarios[8].append(input('Informe o salário do funcionário: '))

# Se a opção do menu escolhida for '2' (consultar um funcionário):
elif menu == '2':
    # Solicita ao usuário que insira o ID do funcionário a ser consultado.
    id2 = input('Informe o Id do funcionário: ')
    # Verifica se o ID está na lista de IDs de funcionários.
    if id2 in funcionarios[0]:
        # Se estiver na lista, encontra o índice correspondente ao ID e imprime os detalhes desse funcionário.
        i2 = funcionarios[0].index(id2)
        print(f'''{funcionarios[1][i2]} mora em {funcionarios[2][i2]} {funcionarios[3][i2]},
seu email é {funcionarios[4][i2]}, sua idade é {funcionarios[5][i2]} anos,
sua escolaridade é {funcionarios[6][i2]} anos, seu cargo é {funcionarios[7][i2]}
e seu salário é {funcionarios[8][i2]}''')
    else:
        # Se o ID não estiver na lista, informa que o funcionário não está cadastrado.
        print('Funcionário não cadastrado!')

# Se a opção do menu escolhida for '3' (atualizar um funcionário):
elif menu == '3':
    # Solicita ao usuário que insira o ID do funcionário a ser atualizado.
    id3 = input('Informe o Id do funcionário: ')
    # Verifica se o ID está na lista de IDs de funcionários.
    if id3 in funcionarios[0]:
        # Se estiver na lista, encontra o índice correspondente ao ID e solicita ao usuário que insira os novos detalhes do funcionário.
        i3 = funcionarios[0].index(id3)
        nome = input('Informe o nome do funcionário: ')
        funcionarios[1][i3] = nome
        cidade = input('Informe a cidade do funcionário: ')
        funcionarios[2][i3] = cidade
        estado = input('Informe o estado do funcionário: ')
        funcionarios[3][i3] = estado
        email = input('Informe o email do funcionário: ')
        funcionarios[4][i3] = email
        idade = input('Informe a idade do funcionário: ')
        funcionarios[5][i3] = idade
        escolaridade = input('Informe a escolaridade do funcionário: ')
        funcionarios[6][i3] = escolaridade
        cargo = input('Informe o cargo do funcionário: ')
        funcionarios[7][i3] = cargo
        salario = input('Informe o cargo do funcionário: ')
        funcionarios[8][i3] = salario
    else:
        # Se o ID não estiver na lista, informa que o funcionário não está cadastrado.
        print('Funcionário não cadastrado!')

# Se a opção do menu escolhida for '4' (remover um funcionário):
elif menu == '4':
    # Solicita ao usuário que insira o ID do funcionário a ser removido.
    id4 = input('Informe o Id do funcionário: ')
    # Verifica se o ID está na lista de IDs de funcionários.
    if id4 in funcionarios[0]:
        # Se estiver na lista, encontra o índice correspondente ao ID e remove todas as informações desse funcionário.
        i4 = funcionarios[0].index(id4)
        funcionarios[0].pop(i4)
        funcionarios[1].pop(i4)
        funcionarios[2].pop(i4)
        funcionarios[3].pop(i4)
        funcionarios[4].pop(i4)
        funcionarios[5].pop(i4)
        funcionarios[6].pop(i4)
        funcionarios[7].pop(i4)
        funcionarios[8].pop(i4)
    else:
        # Se o ID não estiver na lista, informa que o funcionário não está cadastrado.
        print('Funcionário não cadastrado!')

# Se a opção do menu escolhida não for uma das opções válidas:
else:
    # Informa ao usuário que a opção escolhida é inválida.
    print('Opção inválida!')