# -*- coding: utf-8 -*-
"""Exercício sobre medidas de estatística descritiva para variáveis quantitativas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zEmGlv1x8g4WJQcxELPhrc0CnDWIiDl
"""

import pandas as pd
import numpy as np

url = 'https://docs.google.com/spreadsheets/d/1q64TPaErzCYgXX6Exp1hopq_L2JnRT3j/export?format=csv'
df = pd.read_csv(url)

print("Dados da Planilha:")
print(df.head())

print("\nNomes das Colunas:")
print(df.columns)

df.columns = df.columns.str.strip()

if 'Demissão' in df.columns:
    # Separar os dados em dois grupos: os que pediram demissão e os que não pediram
    demitidos = df[df['Demissão'] == 'SIM']
    nao_demitidos = df[df['Demissão'] == 'NÃO']
else:
    print("A coluna 'Demissão' não foi encontrada. Verifique os nomes das colunas.")

variaveis_quantitativas = [
    'Idade',
    'Diárias recebidas',
    'Distância de Casa',
    'Salário por hora',
    'Renda mensal',
    'Salário Mensal',
    'percentual de aumento de salário',
    'score de performance',
    'Total de anos trabalhados',
    'Anos trabalhados na função atual',
    'Anos desde a última promoção',
    'Anos trabalhando com o atual gestor'
]

def calcular_medidas_descritivas(df, variaveis):
    medidas = {}
    for var in variaveis:
        if var in df.columns:
            medidas[var] = {
                'Média': np.mean(df[var]),
                'Mediana': np.median(df[var]),
                'Desvio Padrão': np.std(df[var]),
                'Mínimo': np.min(df[var]),
                'Máximo': np.max(df[var])
            }
    return pd.DataFrame(medidas)

if 'Demissão' in df.columns:
    medidas_demitidos = calcular_medidas_descritivas(demitidos, variaveis_quantitativas)
    medidas_nao_demitidos = calcular_medidas_descritivas(nao_demitidos, variaveis_quantitativas)

    print("\nMedidas Descritivas - Funcionários que Pediram Demissão")
    print(medidas_demitidos)

    print("\nMedidas Descritivas - Funcionários que Não Pediram Demissão")
    print(medidas_nao_demitidos)