# -*- coding: utf-8 -*-
"""Projeto Bucket e tratamento de dados Aline Melo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BhFsXniKRaMDBwaubXoUrNr1xPY568A
"""

import pandas as pd

from io import StringIO

df = pd.read_csv('https://storage.googleapis.com/desafio-02/dados%20brutos%2002/dados_inconsistentes%20-%20dados_inconsistentes.csv.csv')
display(df)

listas = {col: df[col].tolist() for col in df.columns}

registros_completos = []
for i in range(len(listas['nome'])):
    if all(pd.notnull(listas[col][i]) and listas[col][i] != "" for col in listas):
        registros_completos.append(i)

for col in listas:
    listas[col] = [listas[col][i] for i in registros_completos]

df_tratado = pd.DataFrame(listas)

df_tratado.to_csv('dados_inconsistentes - dados_inconsistentes.csv', index=False)

from google.colab import auth
from google.cloud import storage
auth.authenticate_user()
project_id = 'projeto-aline-440013'
!gcloud config set project {project_id}
client = storage.Client()
bucket_name = 'desafio-02'
bucket = client.bucket(bucket_name)
source_file_name = 'dados_inconsistentes - dados_inconsistentes.csv'
destination_blob_name = 'dados tratados 02/dados_inconsistentes - dados_inconsistentes.csv'
blob = bucket.blob(destination_blob_name)
blob.upload_from_filename(source_file_name)

print("Arquivo enviado com sucesso para a pasta 'dados tratados 02'.")

df_tratado = df.dropna()
df_tratado = df_tratado[~df_tratado.isin(['erro', ''])].dropna(how='all')