# -*- coding: utf-8 -*-
"""medidas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZWvq5seB96LNS3Gj_PY9jShl7Cccw0x
"""

def media(n1, n2):
  media = (n1 +n2) / 2
  return media

def imc(peso, altura):
  imc = peso/altura**2
  return imc