# -*- coding: utf-8 -*-
"""teste

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXfph4yNs5_IMTWj2dIf0Ykzao9PSF02
"""

import medidas

medidas.media(10, 8)

import medidas as md

md.media(10, 8)

md.imc(87, 1.85)