# -*- coding: utf-8 -*-
"""matfin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EtngEpNXU_2Fu6ESfIbluyGjdkK4NE_I
"""

def vf():
  vp = float(input('Informe o valor do empréstimo em R$: '))
  i = (float(input('Informe a taxa em formato %: ')))/100
  n = int(input('Informe o tempo do empréstimo: '))
  vf = vp * (1+i)**n
  return vf

def vp():
  vf = float(input('Informe o valor futuro em R$: '))
  i = (float(input('Informe a taxa em formato %: ')))/100
  n = int(input('Informe o tempo do empréstimo: '))
  vp = vf /((1+i)**n)
  return vp

def i():
  vp = float(input('Informe o valor do empréstimo em R$: '))
  vf = float(input('Informe o valor futuro em R$: '))
  n = int(input('Informe o tempo do empréstimo: '))
  i = (((vf/vp)**(1/n))-1)*100
  return i

def pmt():
  i = (float(input('Informe a taxa em formato %: ')))/100
  vp = float(input('Informe o valor do empréstimo em R$: '))
  n = int(input('Informe o tempo do empréstimo: '))
  pmt = vp * ((((1+i)**n)*i)/(((1+i)**n) - 1))
  return pmt