# -*- coding: utf-8 -*-
"""teste2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oKGHU1IZUi7uYfo72C0Vg2jRceSHH2q
"""

import matfin as mf

mf.vf()

mf.vp()

mf.i()

mf.pmt()