# -*- coding: utf-8 -*-
"""AED

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHM8VvecCTfWldzFt1wXoRhQeRkF1ngC
"""

import pandas as pd
import numpy as np
import statistics as st

# importando uma tabela a partir de um link da internet
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSU9iI1TDNfDVCbv4FCa9TDhBmgQKsDtrW6n7R6ndyFzDo2Qeq8sJj-RhJnzKuwm5Lx1f8n7r7ig7Vs/pub?gid=0&single=true&output=csv')
display(df)

idades = list(df['idade'])
salarios = list(df['salario'])
notas = list(df['nota'])

"""# 1 - Medidas de Tendência Central"""

# Média aritmética
medianp = np.mean(idades)
print(medianp)
mediast = st.mean(idades)
print(mediast)

# Mediana
mediananp = np.median(idades)
print(mediananp)
medianast = st.median(idades)
print(medianast)

# Moda
#modanp = np.mode(idades) (não temos o atributo moda no numpy)
#print(modanp)
modast = st.mode(idades)
print(modast)

"""# 2 Medidas de dispersão"""

# Variância
variancianp = np.var(idades,ddof=1) # no numpy a variancia amostral precisa do parametro ddof=1
print(variancianp)
varianciast = st.variance(idades)
print(varianciast)

# Desvio Padrão
desvionp = np.std(idades, ddof=1)
print(desvionp)
desviost = st.stdev(idades)
print(round(desviost,3))

"""# 3 - Medidas Separatrizes"""

# Valor Mínimo
minnp = np.min(idades)
print(minnp)
#minst = st.min(idades) nesta biblioteca não temos o atributo min
#print(minst)

# 1º Quartil - Q1
q1np = np.quantile(idades,0.25)
print(q1np)
q1st = st.quantiles(idades)[0]
print(q1st)

# 2º Quartil - Q2
q2np = np.quantile(idades,0.5)
print(q2np)
q2st = st.quantiles(idades)[1]
print(q2st)

# 3º Quartil - Q3
q3np = np.quantile(idades,0.75)
print(q3np)
q3st = st.quantiles(idades)[2]
print(q3st)

# Valor Máximo
maxnp = np.max(idades)
print(maxnp)
# maxst = st.max(idades) # nesta biblioteca não temos o atributo max
# print(maxst)

# Amplitude Interquartílica - AIQ
aiqnp = q3np - q1np
print(aiqnp)
aiqst = q3st - q1st
print(aiqst)

# Limite inferior - LI
linp = q1np - (1.5 * aiqnp)
print(linp)
linst = q1st - (1.5 * aiqst)
print(linst)

# Limite Superior - LS
lsnp = q3np + (1.5 * aiqnp)
print(lsnp)
lsst = q3st + (1.5 * aiqst)
print(lsst)

"""# 4 - Correlação"""

correlnp = np.corrcoef(idades,salarios)
print(correlnp[0][1])
correlst = st.correlation(idades,salarios)
print(correlst)